export * from '../components/DashboardShared'
export * from './SuperAdminDashboard'
export * from './HospitalAdminDashboard'
export * from './DoctorDashboard'
export * from './NurseDashboard'
export * from './ReceptionDashboard'
export * from './AccountantDashboard'
export * from './PatientDashboard'
