export {
  fetchNotificationRules,
  updateNotificationRule,
  fetchNotificationTemplates,
  updateNotificationTemplate,
  sendTestNotification,
  fetchNotificationFailures,
  fetchNotificationPreferences,
  updateNotificationPreferences,
  fetchNotifications,
  fetchUnreadCount,
  markNotificationAsRead,
  markNotificationAsUnread,
  markAllNotificationsAsRead,
  deleteNotification,
} from "../api/notification.api";
