import type {
  NotificationRule,
  NotificationRulePayload,
  NotificationTemplate,
  NotificationTemplatePayload,
  NotificationPreferences,
  NotificationPreferencesPayload,
  NotificationPageResponse,
  UnreadCountResponse,
  NotificationDetailResponse,
  TestNotificationResponse,
  NotificationFailureRecord,
  MarkReadResponse,
  TestNotificationPayload,
  InternalNotificationPayload,
} from "../types/notifications.types";

export {
  fetchNotificationRules,
  updateNotificationRule,
  fetchNotificationTemplates,
  updateNotificationTemplate,
  sendTestNotification,
  fetchNotificationFailures,
  fetchNotificationPreferences,
  updateNotificationPreferences,
  fetchNotifications,
  fetchUnreadCount,
  markNotificationAsRead,
  markNotificationAsUnread,
  markAllNotificationsAsRead,
  deleteNotification,
} from "../api/notification.api";

export type {
  NotificationRule,
  NotificationRulePayload,
  NotificationTemplate,
  NotificationTemplatePayload,
  NotificationPreferences,
  NotificationPreferencesPayload,
  NotificationPageResponse,
  UnreadCountResponse,
  NotificationDetailResponse,
  TestNotificationResponse,
  NotificationFailureRecord,
  MarkReadResponse,
  TestNotificationPayload,
  InternalNotificationPayload,
};
