import type { AppStatus } from "../types/app.types";

export const TREND_PATIENTS = [
  { v: 98 },
  { v: 115 },
  { v: 108 },
  { v: 132 },
  { v: 119 },
  { v: 138 },
  { v: 142 },
];

export const TREND_QUEUE = [
  { v: 22 },
  { v: 19 },
  { v: 24 },
  { v: 16 },
  { v: 21 },
  { v: 14 },
  { v: 18 },
];

export const TREND_REVENUE = [
  { v: 18 },
  { v: 21 },
  { v: 19 },
  { v: 24 },
  { v: 22 },
  { v: 23 },
  { v: 24.8 },
];

export const TREND_DOCTORS = [
  { v: 14 },
  { v: 16 },
  { v: 15 },
  { v: 17 },
  { v: 16 },
  { v: 18 },
  { v: 18 },
];

export const APPOINTMENTS = [
  {
    id: 1,
    time: "09:00",
    patient: "Sarah Mitchell",
    age: 34,
    gender: "F",
    complaint: "Chest Pain",
    doctor: "Dr. A. Mehta",
    status: "waiting" as AppStatus,
    priority: "high",
    mrn: "MRN-001",
  },
  {
    id: 2,
    time: "09:30",
    patient: "James Thornton",
    age: 67,
    gender: "M",
    complaint: "Diabetes Follow-up",
    doctor: "Dr. P. Sharma",
    status: "in-progress" as AppStatus,
    priority: "normal",
    mrn: "MRN-002",
  },
  {
    id: 3,
    time: "10:00",
    patient: "Emma Reyes",
    age: 28,
    gender: "F",
    complaint: "Prenatal Visit",
    doctor: "Dr. S. Patel",
    status: "checked-in" as AppStatus,
    priority: "normal",
    mrn: "MRN-003",
  },
  {
    id: 4,
    time: "10:30",
    patient: "Robert Chen",
    age: 52,
    gender: "M",
    complaint: "Cardiology Review",
    doctor: "Dr. A. Mehta",
    status: "scheduled" as AppStatus,
    priority: "normal",
    mrn: "MRN-004",
  },
  {
    id: 5,
    time: "11:00",
    patient: "Aisha Kumar",
    age: 41,
    gender: "F",
    complaint: "Migraine",
    doctor: "Dr. R. Kapoor",
    status: "scheduled" as AppStatus,
    priority: "normal",
    mrn: "MRN-005",
  },
  {
    id: 6,
    time: "11:30",
    patient: "David Walsh",
    age: 38,
    gender: "M",
    complaint: "Back Pain",
    doctor: "Dr. P. Sharma",
    status: "scheduled" as AppStatus,
    priority: "low",
    mrn: "MRN-006",
  },
  {
    id: 7,
    time: "14:00",
    patient: "Lily Anderson",
    age: 55,
    gender: "F",
    complaint: "Thyroid Review",
    doctor: "Dr. S. Patel",
    status: "scheduled" as AppStatus,
    priority: "normal",
    mrn: "MRN-007",
  },
  {
    id: 8,
    time: "14:30",
    patient: "Marcus Brown",
    age: 71,
    gender: "M",
    complaint: "Hypertension F/U",
    doctor: "Dr. A. Mehta",
    status: "scheduled" as AppStatus,
    priority: "normal",
    mrn: "MRN-008",
  },
  {
    id: 9,
    time: "15:00",
    patient: "Nina Patel",
    age: 29,
    gender: "F",
    complaint: "Skin Allergy",
    doctor: "Dr. R. Kapoor",
    status: "completed" as AppStatus,
    priority: "low",
    mrn: "MRN-009",
  },
  {
    id: 10,
    time: "15:30",
    patient: "Carlos Mendez",
    age: 63,
    gender: "M",
    complaint: "Joint Pain",
    doctor: "Dr. P. Sharma",
    status: "completed" as AppStatus,
    priority: "normal",
    mrn: "MRN-010",
  },
];

export const DEPARTMENTS = [
  {
    name: "OPD — General",
    capacity: 87,
    active: 22,
    total: 25,
    color: "#0D47A1",
  },
  { name: "Cardiology", capacity: 68, active: 17, total: 25, color: "#EF4444" },
  { name: "Pediatrics", capacity: 43, active: 9, total: 21, color: "#009688" },
  { name: "Gynecology", capacity: 70, active: 14, total: 20, color: "#9C27B0" },
  { name: "Neurology", capacity: 55, active: 11, total: 20, color: "#F59E0B" },
];

export const JOURNEY_STEPS = [
  { step: "Registration", count: 12, done: false },
  { step: "Appointment", count: 142, done: false },
  { step: "Check-In", count: 89, done: false },
  { step: "Vitals", count: 34, done: false },
  { step: "Consultation", count: 28, done: false },
  { step: "Prescription", count: 21, done: false },
  { step: "Billing", count: 15, done: false },
  { step: "Completed", count: 48, done: true },
];

export const STATUS_CONFIG: Record<
  AppStatus,
  { bg: string; text: string; dot: string; label: string }
> = {
  scheduled: {
    bg: "bg-slate-50",
    text: "text-slate-600",
    dot: "bg-slate-400",
    label: "Scheduled",
  },
  "checked-in": {
    bg: "bg-blue-50",
    text: "text-blue-700",
    dot: "bg-blue-500",
    label: "Checked In",
  },
  waiting: {
    bg: "bg-amber-50",
    text: "text-amber-700",
    dot: "bg-amber-500",
    label: "Waiting",
  },
  "in-progress": {
    bg: "bg-teal-50",
    text: "text-teal-700",
    dot: "bg-teal-500",
    label: "In Progress",
  },
  completed: {
    bg: "bg-green-50",
    text: "text-green-700",
    dot: "bg-green-500",
    label: "Completed",
  },
  cancelled: {
    bg: "bg-red-50",
    text: "text-red-700",
    dot: "bg-red-400",
    label: "Cancelled",
  },
};
