import type {
  DoctorRecord,
  DoctorAppointment,
  DoctorPatient,
  WeeklySchedule,
  DoctorTimeline,
  VitalSign,
  Medication,
  PrescriptionRecord,
} from "../types/doctors.types";

export const PP = "Poppins, sans-serif";
export const RB = "Roboto, sans-serif";

export const INITIAL_DOCTORS: DoctorRecord[] = [
  {
    id: "DOC-1001",
    empId: "EMP-1001",
    regNumber: "MCI-REG-847291",
    name: "Dr. Arjun Mehta",
    gender: "Male",
    department: "Cardiology",
    specialty: "Interventional Cardiology",
    qualification: "MBBS, MD, DM (Cardiology)",
    designation: "Senior Consultant",
    experienceYrs: 14,
    consultationFee: 150,
    followUpFee: 80,
    slotDuration: "15 Minutes",
    availability: "Available Today",
    status: "Active",
    email: "arjun.mehta@citygeneral.org",
    phone: "+1 (555) 234-5678",
    address: "742 Evergreen Terrace, Suite 104",
    dob: "1985-05-14",
    opdRoom: "OPD Room 104",
    joinedDate: "2020-03-15",
    shiftTimings: "09:00 AM - 04:00 PM",
    workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    bio: "Senior Interventional Cardiologist with 14+ years of expertise in coronary angioplasty, pacemaker implantations, and complex cardiovascular management.",
  },
  {
    id: "DOC-1002",
    empId: "EMP-1005",
    regNumber: "MCI-REG-938102",
    name: "Dr. Priya Sharma",
    gender: "Female",
    department: "General Medicine",
    specialty: "Internal Medicine",
    qualification: "MBBS, MD (Medicine)",
    designation: "Consultant Physician",
    experienceYrs: 10,
    consultationFee: 120,
    followUpFee: 60,
    slotDuration: "15 Minutes",
    availability: "Available Today",
    status: "Active",
    email: "p.sharma@citygeneral.org",
    phone: "+1 (555) 678-9012",
    address: "102 Medical Plaza Blvd",
    dob: "1988-09-22",
    opdRoom: "OPD Room 202",
    joinedDate: "2021-06-10",
    shiftTimings: "08:30 AM - 03:30 PM",
    workingDays: ["Mon", "Tue", "Wed", "Fri", "Sat"],
    bio: "Specialist in internal medicine, metabolic disorders, hypertension management, and preventative health diagnostics.",
  },
  {
    id: "DOC-1003",
    empId: "EMP-1009",
    regNumber: "MCI-REG-746201",
    name: "Dr. Rajesh Kapoor",
    gender: "Male",
    department: "Neurology",
    specialty: "Clinical Neurology",
    qualification: "MBBS, MD, DNB (Neurology)",
    designation: "Senior Specialist",
    experienceYrs: 16,
    consultationFee: 180,
    followUpFee: 100,
    slotDuration: "20 Minutes",
    availability: "On Duty",
    status: "Active",
    email: "r.kapoor@citygeneral.org",
    phone: "+1 (555) 012-3456",
    address: "55 Neuro Science Way",
    dob: "1982-12-01",
    opdRoom: "OPD Room 305",
    joinedDate: "2019-01-20",
    shiftTimings: "10:00 AM - 05:00 PM",
    workingDays: ["Mon", "Wed", "Thu", "Fri"],
    bio: "Consultant Neurologist specializing in stroke management, epilepsy, neuromuscular disorders, and electroencephalography.",
  },
  {
    id: "DOC-1004",
    empId: "EMP-1014",
    regNumber: "MCI-REG-654321",
    name: "Dr. Ananya Sen",
    gender: "Female",
    department: "Pediatrics",
    specialty: "Pediatric Care & Neonatology",
    qualification: "MBBS, MD (Pediatrics)",
    designation: "Associate Consultant",
    experienceYrs: 8,
    consultationFee: 110,
    followUpFee: 50,
    slotDuration: "15 Minutes",
    availability: "Available Today",
    status: "Active",
    email: "a.sen@citygeneral.org",
    phone: "+1 (555) 345-9876",
    address: "88 Childrens Care Ave",
    dob: "1990-04-18",
    opdRoom: "OPD Room 112",
    joinedDate: "2022-02-14",
    shiftTimings: "09:00 AM - 02:00 PM",
    workingDays: ["Mon", "Tue", "Thu", "Fri", "Sat"],
    bio: "Dedicated pediatrician with special focus on newborn care, pediatric immunizations, and developmental growth tracking.",
  },
  {
    id: "DOC-1005",
    empId: "EMP-1018",
    regNumber: "MCI-REG-543210",
    name: "Dr. Vikramaditya Rao",
    gender: "Male",
    department: "Orthopedics",
    specialty: "Orthopedic Surgery & Joint Replacement",
    qualification: "MBBS, MS (Orthopedics), MCh",
    designation: "Chief of Orthopedics",
    experienceYrs: 18,
    consultationFee: 200,
    followUpFee: 120,
    slotDuration: "30 Minutes",
    availability: "On Call",
    status: "Active",
    email: "v.rao@citygeneral.org",
    phone: "+1 (555) 456-8765",
    address: "12 Ortho Joint Blvd",
    dob: "1979-08-30",
    opdRoom: "OPD Room 401",
    joinedDate: "2017-09-01",
    shiftTimings: "11:00 AM - 06:00 PM",
    workingDays: ["Tue", "Wed", "Fri"],
    bio: "Renowned orthopedic surgeon specializing in total knee/hip joint replacements, arthroscopy, and trauma management.",
  },
  {
    id: "DOC-1006",
    empId: "EMP-1022",
    regNumber: "MCI-REG-432109",
    name: "Dr. Sunita Patel",
    gender: "Female",
    department: "Obstetrics & Gynecology",
    specialty: "Reproductive Health & Maternal Care",
    qualification: "MBBS, MS (OB-GYN)",
    designation: "Senior Consultant",
    experienceYrs: 12,
    consultationFee: 140,
    followUpFee: 70,
    slotDuration: "15 Minutes",
    availability: "On Leave",
    status: "On Leave",
    email: "s.patel@citygeneral.org",
    phone: "+1 (555) 567-7654",
    address: "404 Maternal Wellness Rd",
    dob: "1986-07-11",
    opdRoom: "OPD Room 208",
    joinedDate: "2020-11-05",
    shiftTimings: "09:00 AM - 03:00 PM",
    workingDays: ["Mon", "Wed", "Thu", "Sat"],
    bio: "Obstetrician & Gynecologist with expertise in high-risk pregnancy care, laparoscopic gynecology, and maternal health.",
  },
  {
    id: "DOC-1007",
    empId: "EMP-1025",
    regNumber: "MCI-REG-321098",
    name: "Dr. Siddharth Verma",
    gender: "Male",
    department: "Dermatology",
    specialty: "Clinical & Aesthetic Dermatology",
    qualification: "MBBS, MD (Dermatology)",
    designation: "Junior Consultant",
    experienceYrs: 7,
    consultationFee: 130,
    followUpFee: 65,
    slotDuration: "15 Minutes",
    availability: "Out of Office",
    status: "Active",
    email: "s.verma@citygeneral.org",
    phone: "+1 (555) 678-6543",
    address: "77 Skin Health Lane",
    dob: "1991-03-05",
    opdRoom: "OPD Room 118",
    joinedDate: "2022-08-19",
    shiftTimings: "10:00 AM - 04:00 PM",
    workingDays: ["Mon", "Tue", "Wed", "Fri"],
    bio: "Dermatologist specializing in skin disorder management, laser therapies, and aesthetic dermatology treatments.",
  },
  {
    id: "DOC-1008",
    empId: "EMP-1029",
    regNumber: "MCI-REG-210987",
    name: "Dr. Meera Krishnan",
    gender: "Female",
    department: "ENT",
    specialty: "Otolaryngology & Head-Neck Surgery",
    qualification: "MBBS, MS (ENT)",
    designation: "Consultant Surgeon",
    experienceYrs: 11,
    consultationFee: 125,
    followUpFee: 60,
    slotDuration: "15 Minutes",
    availability: "Available Today",
    status: "Active",
    email: "m.krishnan@citygeneral.org",
    phone: "+1 (555) 789-5432",
    address: "99 ENT Clinic St",
    dob: "1987-11-20",
    opdRoom: "OPD Room 215",
    joinedDate: "2021-01-12",
    shiftTimings: "08:30 AM - 02:30 PM",
    workingDays: ["Mon", "Thu", "Fri", "Sat"],
    bio: "ENT surgeon with extensive experience in endoscopic sinus surgery, audiometry evaluation, and throat care.",
  },
  {
    id: "DOC-1009",
    empId: "EMP-1033",
    regNumber: "MCI-REG-109876",
    name: "Dr. Tariq Mansoor",
    gender: "Male",
    department: "Ophthalmology",
    specialty: "Cornea & Refractive Surgery",
    qualification: "MBBS, MS (Ophthalmology)",
    designation: "Associate Specialist",
    experienceYrs: 9,
    consultationFee: 115,
    followUpFee: 55,
    slotDuration: "15 Minutes",
    availability: "Available Today",
    status: "Active",
    email: "t.mansoor@citygeneral.org",
    phone: "+1 (555) 890-4321",
    address: "33 Vision Park Circle",
    dob: "1989-06-15",
    opdRoom: "OPD Room 310",
    joinedDate: "2022-05-01",
    shiftTimings: "09:30 AM - 04:30 PM",
    workingDays: ["Tue", "Wed", "Thu", "Fri"],
    bio: "Ophthalmic surgeon specializing in cataract phacoemulsification, glaucoma screening, and vision correction.",
  },
  {
    id: "DOC-1010",
    empId: "EMP-1037",
    regNumber: "MCI-REG-987654",
    name: "Dr. Kavita Nair",
    gender: "Female",
    department: "Pulmonology",
    specialty: "Respiratory Medicine",
    qualification: "MBBS, MD (Chest Medicine)",
    designation: "Senior Pulmonologist",
    experienceYrs: 15,
    consultationFee: 160,
    followUpFee: 80,
    slotDuration: "20 Minutes",
    availability: "On Leave",
    status: "Inactive",
    email: "k.nair@citygeneral.org",
    phone: "+1 (555) 901-3210",
    address: "210 Chest Medicine Plaza",
    dob: "1983-02-28",
    opdRoom: "OPD Room 302",
    joinedDate: "2018-04-10",
    shiftTimings: "10:00 AM - 04:00 PM",
    workingDays: ["Mon", "Wed", "Fri"],
    bio: "Senior Pulmonologist focusing on asthma, COPD management, sleep apnea diagnostics, and interventional pulmonology.",
  },
];

export const MOCK_DOCTOR_APPOINTMENTS: DoctorAppointment[] = [
  {
    id: "APT-1024",
    patientId: "PT-2024-001",
    patientName: "Sarah Mitchell",
    gender: "F",
    age: 34,
    date: "March 28, 2024",
    time: "10:30 AM",
    type: "Follow-up Visit",
    status: "Scheduled",
    complaint: "Hypertension monitoring & ECG review",
  },
  {
    id: "APT-1018",
    patientId: "PT-2024-002",
    patientName: "James Thornton",
    gender: "M",
    age: 67,
    date: "March 28, 2024",
    time: "11:15 AM",
    type: "OPD Consultation",
    status: "In Progress",
    complaint: "Chest tightness evaluation",
  },
  {
    id: "APT-0982",
    patientId: "PT-2024-003",
    patientName: "Emma Reyes",
    gender: "F",
    age: 28,
    date: "March 28, 2024",
    time: "02:00 PM",
    type: "Routine Checkup",
    status: "Scheduled",
    complaint: "Post-op cardiac checkup",
  },
  {
    id: "APT-0955",
    patientId: "PT-2024-004",
    patientName: "Robert Chen",
    gender: "M",
    age: 52,
    date: "March 27, 2024",
    time: "09:45 AM",
    type: "OPD Consultation",
    status: "Completed",
    complaint: "Cardiology intake & vitals",
  },
  {
    id: "APT-0912",
    patientId: "PT-2024-005",
    patientName: "Aisha Kumar",
    gender: "F",
    age: 41,
    date: "March 26, 2024",
    time: "04:00 PM",
    type: "Follow-up Visit",
    status: "Completed",
    complaint: "BP medication adjustment",
  },
];

export const MOCK_DOCTOR_PATIENTS: DoctorPatient[] = [
  {
    id: "PT-2024-001",
    name: "Sarah Mitchell",
    gender: "Female",
    age: 34,
    lastVisit: "March 12, 2024",
    status: "Active",
    complaint: "Chest Pain Checkup",
  },
  {
    id: "PT-2024-002",
    name: "James Thornton",
    gender: "Male",
    age: 67,
    lastVisit: "March 10, 2024",
    status: "Active",
    complaint: "Diabetes & BP Follow-up",
  },
  {
    id: "PT-2024-004",
    name: "Robert Chen",
    gender: "Male",
    age: 52,
    lastVisit: "March 05, 2024",
    status: "Active",
    complaint: "Hypertension Review",
  },
  {
    id: "PT-2024-008",
    name: "Marcus Brown",
    gender: "Male",
    age: 71,
    lastVisit: "Feb 20, 2024",
    status: "Admitted",
    complaint: "Angina Evaluation",
  },
  {
    id: "PT-2024-012",
    name: "David Walsh",
    gender: "Male",
    age: 38,
    lastVisit: "Jan 14, 2024",
    status: "Inactive",
    complaint: "Lower Back Pain",
  },
];

export const MOCK_WEEKLY_SCHEDULE: WeeklySchedule[] = [
  {
    day: "Monday",
    available: true,
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    slotDuration: "15 Mins",
  },
  {
    day: "Tuesday",
    available: true,
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    slotDuration: "15 Mins",
  },
  {
    day: "Wednesday",
    available: true,
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    slotDuration: "15 Mins",
  },
  {
    day: "Thursday",
    available: true,
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    slotDuration: "15 Mins",
  },
  {
    day: "Friday",
    available: true,
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    slotDuration: "15 Mins",
  },
  {
    day: "Saturday",
    available: false,
    startTime: "--",
    endTime: "--",
    slotDuration: "--",
  },
  {
    day: "Sunday",
    available: false,
    startTime: "--",
    endTime: "--",
    slotDuration: "--",
  },
];

export const MOCK_DOCTOR_TIMELINE: DoctorTimeline[] = [
  {
    time: "Today, 10:30 AM",
    title: "Appointment Completed",
    desc: "OPD consultation completed for Sarah Mitchell (PT-2024-001).",
    icon: "CheckCircle2" as unknown as React.ElementType,
    type: "appointment",
  },
  {
    time: "Today, 09:15 AM",
    title: "Prescription Issued",
    desc: "Issued Rx-2024-104 (Lisinopril 10mg, Atorvastatin 20mg).",
    icon: "FileText" as unknown as React.ElementType,
    type: "prescription",
  },
  {
    time: "Yesterday, 04:30 PM",
    title: "Schedule Updated",
    desc: "OPD Availability schedule updated for current month by Hospital Admin.",
    icon: "Clock" as unknown as React.ElementType,
    type: "schedule",
  },
  {
    time: "Mar 20, 2024, 02:15 PM",
    title: "Profile Updated",
    desc: "Consultation fee and OPD Room details updated by Admin.",
    icon: "Edit" as unknown as React.ElementType,
    type: "profile",
  },
  {
    time: "Jan 15, 2020, 09:00 AM",
    title: "Doctor Registered",
    desc: "Doctor onboarded into HMS under Cardiology Department (MCI-REG-847291).",
    icon: "Stethoscope" as unknown as React.ElementType,
    type: "registration",
  },
];

export const DEPARTMENTS = [
  "Cardiology",
  "General Medicine",
  "Neurology",
  "Orthopedics",
  "Pediatrics",
  "Obstetrics & Gynecology",
  "Dermatology",
  "ENT",
  "Ophthalmology",
  "Pulmonology",
];

export const SPECIALTIES = [
  "Interventional Cardiology",
  "Internal Medicine",
  "Clinical Neurology",
  "Pediatric Care & Neonatology",
  "Orthopedic Surgery & Joint Replacement",
  "Reproductive Health & Maternal Care",
  "Clinical & Aesthetic Dermatology",
  "Otolaryngology & Head-Neck Surgery",
  "Cornea & Refractive Surgery",
  "Respiratory Medicine",
];

export const VITALS_DATA: VitalSign[] = [
  {
    label: "Blood Pressure",
    value: "145/92",
    unit: "mmHg",
    Icon: "Activity" as unknown as React.ElementType,
    status: "high",
    color: "#EF4444",
    normal: "120/80",
  },
  {
    label: "Heart Rate",
    value: "88",
    unit: "bpm",
    Icon: "Heart" as unknown as React.ElementType,
    status: "normal",
    color: "#009688",
    normal: "60–100",
  },
  {
    label: "Temperature",
    value: "37.2",
    unit: "°C",
    Icon: "Thermometer" as unknown as React.ElementType,
    status: "normal",
    color: "#009688",
    normal: "36.5–37.5",
  },
  {
    label: "SpO₂",
    value: "97",
    unit: "%",
    Icon: "Droplets" as unknown as React.ElementType,
    status: "normal",
    color: "#009688",
    normal: ">95",
  },
];

export const MEDICATIONS: Medication[] = [
  {
    id: 1,
    name: "Amlodipine",
    dose: "5mg",
    freq: "Once daily",
    route: "Oral",
    status: "active",
    refill: "22 days",
  },
  {
    id: 2,
    name: "Metformin",
    dose: "500mg",
    freq: "Twice daily",
    route: "Oral",
    status: "active",
    refill: "15 days",
  },
  {
    id: 3,
    name: "Atorvastatin",
    dose: "20mg",
    freq: "Once nightly",
    route: "Oral",
    status: "active",
    refill: "30 days",
  },
  {
    id: 4,
    name: "Aspirin",
    dose: "75mg",
    freq: "Once daily",
    route: "Oral",
    status: "active",
    refill: "28 days",
  },
  {
    id: 5,
    name: "GTN Spray",
    dose: "0.4mg",
    freq: "PRN chest pain",
    route: "Sublingual",
    status: "prn",
    refill: "60 days",
  },
];

export const WEEKLY_CONSULTATIONS = [
  { day: "Mon", count: 18 },
  { day: "Tue", count: 22 },
  { day: "Wed", count: 17 },
  { day: "Thu", count: 25 },
  { day: "Fri", count: 21 },
  { day: "Sat", count: 9 },
  { day: "Sun", count: 0 },
];

export const TIMELINE = [
  {
    time: "08:45",
    event: "Patient registered at reception",
    by: "Receptionist",
  },
  { time: "09:00", event: "Appointment confirmed", by: "System" },
  { time: "09:05", event: "Checked in — OPD Wing A", by: "Receptionist" },
  {
    time: "09:12",
    event: "Vitals recorded by nursing staff",
    by: "Nurse R. Singh",
  },
  { time: "09:20", event: "Consultation started", by: "Dr. A. Mehta" },
];

export const MY_PRESCRIPTIONS_DATA: PrescriptionRecord[] = [
  {
    id: "RX-2026-0891",
    patientName: "Sarah Mitchell",
    mrn: "MRN-892101",
    consultationId: "CNS-1001",
    department: "Cardiology",
    consultationDate: "24 Jul 2026",
    medicineCount: 4,
    followup: true,
    followupDate: "31 Jul 2026",
    status: "Issued",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Angina Pectoris, unspecified (I20.9)",
    medicinesList: [
      { name: "Amlodipine", dose: "5mg", freq: "Once Daily" },
      { name: "Metformin", dose: "500mg", freq: "Twice Daily" },
      { name: "Atorvastatin", dose: "20mg", freq: "Once Nightly" },
      { name: "Aspirin", dose: "75mg", freq: "Once Daily" },
    ],
  },
  {
    id: "RX-2026-0888",
    patientName: "James Thornton",
    mrn: "MRN-772102",
    consultationId: "CNS-1004",
    department: "Cardiology",
    consultationDate: "24 Jul 2026",
    medicineCount: 2,
    followup: true,
    followupDate: "07 Aug 2026",
    status: "Draft",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Essential Hypertension (I10)",
    medicinesList: [
      { name: "Ramipril", dose: "2.5mg", freq: "Once Daily" },
      {
        name: "Hydrochlorothiazide",
        dose: "12.5mg",
        freq: "Once Daily Morning",
      },
    ],
  },
  {
    id: "RX-2026-0872",
    patientName: "Marcus Brown",
    mrn: "MRN-551980",
    consultationId: "CNS-0988",
    department: "Cardiology",
    consultationDate: "23 Jul 2026",
    medicineCount: 3,
    followup: false,
    status: "Completed",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Type 2 Diabetes Mellitus (E11.9)",
    medicinesList: [
      { name: "Glyburide", dose: "5mg", freq: "Twice Daily" },
      { name: "Metformin", dose: "1000mg", freq: "Twice Daily" },
      { name: "Empagliflozin", dose: "10mg", freq: "Once Daily" },
    ],
  },
  {
    id: "RX-2026-0865",
    patientName: "Robert Chen",
    mrn: "MRN-442890",
    consultationId: "CNS-0975",
    department: "Cardiology",
    consultationDate: "22 Jul 2026",
    medicineCount: 2,
    followup: true,
    followupDate: "05 Aug 2026",
    status: "Issued",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Hyperlipidemia, unspecified (E78.5)",
    medicinesList: [
      { name: "Rosuvastatin", dose: "10mg", freq: "Once Nightly" },
      { name: "Ezetimibe", dose: "10mg", freq: "Once Daily" },
    ],
  },
  {
    id: "RX-2026-0850",
    patientName: "Emma Reyes",
    mrn: "MRN-331002",
    consultationId: "CNS-0960",
    department: "Cardiology",
    consultationDate: "21 Jul 2026",
    medicineCount: 5,
    followup: false,
    status: "Cancelled",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Chest Pain, unspecified (R07.9)",
    medicinesList: [
      { name: "Pantoprazole", dose: "40mg", freq: "Once Daily" },
      { name: "Antacid Gel", dose: "10ml", freq: "TID PRN" },
    ],
  },
  {
    id: "RX-2026-0812",
    patientName: "David Walsh",
    mrn: "MRN-112093",
    consultationId: "CNS-0910",
    department: "Cardiology",
    consultationDate: "18 Jul 2026",
    medicineCount: 1,
    followup: false,
    status: "Archived",
    doctorName: "Dr. Arjun Mehta",
    diagnosis: "Acute Coronary Syndrome follow up",
    medicinesList: [{ name: "Clopidogrel", dose: "75mg", freq: "Once Daily" }],
  },
];

export const FREQUENCY_OPTIONS = [
  "Once Daily",
  "Twice Daily",
  "Three Times Daily",
  "Every 6 Hours",
  "Every 8 Hours",
  "SOS",
  "Custom",
];

export const ROUTE_OPTIONS = [
  "Oral",
  "Injection",
  "IV",
  "Topical",
  "Eye Drops",
  "Ear Drops",
  "Nasal",
  "Inhalation",
];

export const COMMON_MEDICINES = [
  "Amlodipine",
  "Metformin",
  "Atorvastatin",
  "Aspirin",
  "Ramipril",
  "Hydrochlorothiazide",
  "Rosuvastatin",
  "Pantoprazole",
  "Clopidogrel",
  "Losartan",
  "Omeprazole",
  "Amoxicillin",
  "Paracetamol",
  "Ibuprofen",
];
