import {
  UserCheck,
  Calendar,
  Stethoscope,
  Pill,
  FileText,
  Receipt,
} from "lucide-react";

import type {
  VisitRecord,
  PatientAppointment,
  BookingDoctor,
  MedicalVisitRecord,
  PrescriptionRecord,
  PatientInvoice,
  PaymentHistoryRecord,
} from "../types/patient.types";

export const PP = "'Poppins', system-ui, sans-serif";

export const RB = "'Roboto', system-ui, sans-serif";

export const MOCK_VISIT_HISTORY: VisitRecord[] = [
  {
    id: "VIS-2024-001",
    visitDate: "Mar 12, 2024",
    visitTime: "10:30 AM",
    department: "Cardiology",
    doctor: "Dr. Arjun Mehta",
    chiefComplaint: "Chest tightness & exertion fatigue",
    diagnosis: "Mild Hypertension, R/O Angina",
    prescriptionIssued: true,
    prescriptionCount: 2,
    prescriptions: [
      "Amlodipine 5mg - 1 Tab OD (Morning)",
      "Atorvastatin 20mg - 1 Tab HS (Night)",
    ],
    status: "Completed",
    vitals: { bp: "145/92 mmHg", hr: "88 bpm", temp: "37.2 °C", spo2: "97%" },
    clinicalNotes:
      "Patient reported occasional chest tightness after mild exertion. BP elevated at 145/92 mmHg. EKG shows normal sinus rhythm. Prescribed BP management regime and scheduled follow-up in 14 days.",
  },
  {
    id: "VIS-2024-002",
    visitDate: "Feb 28, 2024",
    visitTime: "02:15 PM",
    department: "General Medicine",
    doctor: "Dr. Priya Sharma",
    chiefComplaint: "Productive cough, fever (4 days)",
    diagnosis: "Acute Bronchitis",
    prescriptionIssued: true,
    prescriptionCount: 3,
    prescriptions: [
      "Amoxicillin 500mg - 1 Cap TDS (7 Days)",
      "Paracetamol 500mg - 1 Tab SOS",
      "Benadryl Cough Syrup - 10ml BD",
    ],
    status: "Completed",
    vitals: { bp: "122/80 mmHg", hr: "76 bpm", temp: "38.1 °C", spo2: "98%" },
    clinicalNotes:
      "Presenting with productive cough, fever, and generalized fatigue for 4 days. Auscultation reveals bilateral rhonchi. Prescribed course of antibiotics and supportive therapy.",
  },
  {
    id: "VIS-2024-003",
    visitDate: "Jan 15, 2024",
    visitTime: "11:00 AM",
    department: "Cardiology",
    doctor: "Dr. Arjun Mehta",
    chiefComplaint: "Routine annual cardiac review",
    diagnosis: "Annual Cardiac Check-up",
    prescriptionIssued: true,
    prescriptionCount: 1,
    prescriptions: ["Rosuvastatin 10mg - 1 Tab HS"],
    status: "Completed",
    vitals: { bp: "130/84 mmHg", hr: "72 bpm", temp: "36.8 °C", spo2: "99%" },
    clinicalNotes:
      "Routine annual check-up. ECG normal. Treadmill test negative for inducible ischemia. Lipid profile shows borderline high LDL. Advised low-cholesterol diet and regular aerobic exercise.",
  },
  {
    id: "VIS-2023-098",
    visitDate: "Nov 20, 2023",
    visitTime: "09:45 AM",
    department: "Neurology",
    doctor: "Dr. Rajesh Kapoor",
    chiefComplaint: "Occasional tension headaches",
    diagnosis: "Tension Headache, Stress",
    prescriptionIssued: true,
    prescriptionCount: 2,
    prescriptions: [
      "Naproxen 250mg - 1 Tab SOS",
      "Multivitamin B-Complex - 1 Cap OD",
    ],
    status: "Follow-up Required",
    vitals: { bp: "125/82 mmHg", hr: "78 bpm", temp: "36.9 °C", spo2: "98%" },
    clinicalNotes:
      "Bilateral tight band-like headache reported during work stress. No focal neurological deficits. Advised stress management, hydration, and posture correction.",
  },
  {
    id: "VIS-2023-074",
    visitDate: "Aug 10, 2023",
    visitTime: "04:00 PM",
    department: "Orthopedics",
    doctor: "Dr. Sunita Patel",
    chiefComplaint: "Right knee stiffness after prolonged sitting",
    diagnosis: "Early Osteoarthritis Knee",
    prescriptionIssued: false,
    prescriptionCount: 0,
    prescriptions: [],
    status: "Completed",
    vitals: { bp: "118/76 mmHg", hr: "70 bpm", temp: "36.7 °C", spo2: "99%" },
    clinicalNotes:
      "Mild crepitus in right knee joint. Physical examination shows joint sensitivity. Referred to physiotherapy for quadriceps strengthening. No oral NSAIDs required at present.",
  },
];

export const TIMELINE_EVENTS = [
  {
    id: 1,
    event: "Patient Registered",
    date: "Oct 24, 2024",
    time: "09:00 AM",
    doctor: "Reception",
    dept: "Front Desk",
    status: "Completed",
    color: "text-[#0D47A1] bg-blue-50",
    icon: UserCheck,
  },
  {
    id: 2,
    event: "Appointment Booked",
    date: "Oct 24, 2024",
    time: "09:15 AM",
    doctor: "Dr. A. Mehta",
    dept: "Cardiology",
    status: "Completed",
    color: "text-[#009688] bg-teal-50",
    icon: Calendar,
  },
  {
    id: 3,
    event: "Consultation Completed",
    date: "Oct 25, 2024",
    time: "10:30 AM",
    doctor: "Dr. A. Mehta",
    dept: "Cardiology",
    status: "Completed",
    color: "text-[#4DB6AC] bg-teal-50",
    icon: Stethoscope,
  },
  {
    id: 4,
    event: "Prescription Issued",
    date: "Oct 25, 2024",
    time: "10:45 AM",
    doctor: "Dr. A. Mehta",
    dept: "Pharmacy",
    status: "Completed",
    color: "text-violet-600 bg-violet-50",
    icon: Pill,
  },
  {
    id: 5,
    event: "Bill Generated",
    date: "Oct 25, 2024",
    time: "11:00 AM",
    doctor: "Billing Staff",
    dept: "Billing",
    status: "Pending",
    color: "text-amber-600 bg-amber-50",
    icon: FileText,
  },
  {
    id: 6,
    event: "Payment Completed",
    date: "Oct 25, 2024",
    time: "11:30 AM",
    doctor: "Billing Staff",
    dept: "Billing",
    status: "Completed",
    color: "text-[#66BB6A] bg-green-50",
    icon: Receipt,
  },
];

export const INITIAL_PATIENT_APPOINTMENTS: PatientAppointment[] = [
  {
    id: "APT-2025-001",
    date: "2025-03-15",
    time: "10:30 AM",
    doctor: "Dr. Arjun Mehta",
    specialty: "Senior Cardiologist",
    department: "Cardiology",
    visitType: "In-Person OPD",
    status: "Confirmed",
    roomLocation: "Wing A, OPD Room 204",
    reason: "Follow-up for chest tightness and blood pressure monitoring",
    notes: "Patient requested morning slot. Routine ECG pre-check scheduled.",
    consultationStatus: "Scheduled",
    prescriptionStatus: "Pending Consultation",
    billingStatus: "Paid ($97.60)",
    billingAmount: "$97.60",
  },
  {
    id: "APT-2025-002",
    date: "2025-03-22",
    time: "02:00 PM",
    doctor: "Dr. Priya Sharma",
    specialty: "Endocrinologist",
    department: "General Medicine",
    visitType: "Follow-up OPD",
    status: "Scheduled",
    roomLocation: "Wing A, OPD Room 202",
    reason: "Diabetes HbA1c 3-month review and medication adjustment",
    notes: "Please report to Reception 10 minutes prior to session.",
    consultationStatus: "Scheduled",
    prescriptionStatus: "N/A",
    billingStatus: "Pending ($45.00)",
    billingAmount: "$45.00",
  },
  {
    id: "APT-2025-003",
    date: "2025-03-28",
    time: "11:15 AM",
    doctor: "Dr. Rajesh Kapoor",
    specialty: "Neurologist",
    department: "Neurology",
    visitType: "In-Person OPD",
    status: "Pending",
    roomLocation: "Wing B, Room 108",
    reason: "Migraine evaluation & EEG test review",
    notes: "Awaiting hospital admin confirmation for doctor schedule.",
    consultationStatus: "Pending",
    prescriptionStatus: "N/A",
    billingStatus: "Unpaid ($120.00)",
    billingAmount: "$120.00",
  },
  {
    id: "APT-2025-004",
    date: "2025-03-12",
    time: "09:00 AM",
    doctor: "Dr. Arjun Mehta",
    specialty: "Senior Cardiologist",
    department: "Cardiology",
    visitType: "In-Person OPD",
    status: "Completed",
    roomLocation: "Wing A, OPD Room 204",
    reason: "Chest pain evaluation",
    notes: "ECG and lipid panel ordered. Prescribed Metoprolol 25mg.",
    consultationStatus: "Completed",
    prescriptionStatus: "Issued (Rx-8910)",
    billingStatus: "Paid ($97.60)",
    billingAmount: "$97.60",
  },
  {
    id: "APT-2025-005",
    date: "2025-02-20",
    time: "03:30 PM",
    doctor: "Dr. Arjun Mehta",
    specialty: "Senior Cardiologist",
    department: "Cardiology",
    visitType: "In-Person OPD",
    status: "Completed",
    roomLocation: "Wing A, OPD Room 204",
    reason: "Routine cardiac checkup",
    notes: "Normal cardiac rhythm observed. Stable progress.",
    consultationStatus: "Completed",
    prescriptionStatus: "Issued (Rx-8421)",
    billingStatus: "Paid ($85.00)",
    billingAmount: "$85.00",
  },
  {
    id: "APT-2025-006",
    date: "2025-01-18",
    time: "10:00 AM",
    doctor: "Dr. Sunita Patel",
    specialty: "Gynecologist",
    department: "Gynecology",
    visitType: "In-Person OPD",
    status: "Cancelled",
    roomLocation: "Wing C, Room 302",
    reason: "Annual wellness exam",
    notes: "Cancelled by patient due to emergency travel.",
    consultationStatus: "Cancelled",
    prescriptionStatus: "N/A",
    billingStatus: "Refunded ($50.00)",
    billingAmount: "$0.00",
  },
];

export const MOCK_BOOKING_DOCTORS: BookingDoctor[] = [
  {
    id: "DOC-1",
    name: "Dr. Arjun Mehta",
    qualification: "MD, DM (Cardiology), FACC",
    specialization: "Senior Interventional Cardiologist",
    department: "Cardiology",
    experience: "12+ Years Exp.",
    consultationFee: "$65.00",
    availability: "Available Today (6 Slots)",
    rating: "4.9",
    reviewCount: 128,
    avatar: "AM",
    availableToday: true,
  },
  {
    id: "DOC-2",
    name: "Dr. Priya Sharma",
    qualification: "MD (General Medicine), DNB",
    specialization: "Senior Physician & Diabetologist",
    department: "General Medicine",
    experience: "9+ Years Exp.",
    consultationFee: "$50.00",
    availability: "Available Today (8 Slots)",
    rating: "4.8",
    reviewCount: 94,
    avatar: "PS",
    availableToday: true,
  },
  {
    id: "DOC-3",
    name: "Dr. Rajesh Kapoor",
    qualification: "MD, DM (Neurology)",
    specialization: "Consultant Neurologist",
    department: "Neurology",
    experience: "15+ Years Exp.",
    consultationFee: "$80.00",
    availability: "Available Tomorrow (4 Slots)",
    rating: "4.9",
    reviewCount: 156,
    avatar: "RK",
    availableToday: false,
  },
  {
    id: "DOC-4",
    name: "Dr. Sunita Patel",
    qualification: "MS (Obs & Gynae)",
    specialization: "Senior Gynecologist & Obstetrician",
    department: "Gynecology",
    experience: "10+ Years Exp.",
    consultationFee: "$60.00",
    availability: "Available Today (5 Slots)",
    rating: "4.7",
    reviewCount: 82,
    avatar: "SP",
    availableToday: true,
  },
  {
    id: "DOC-5",
    name: "Dr. Vikram Sen",
    qualification: "MD (Pediatrics)",
    specialization: "Consultant Pediatrician",
    department: "Pediatrics",
    experience: "8+ Years Exp.",
    consultationFee: "$55.00",
    availability: "Available Today (7 Slots)",
    rating: "4.9",
    reviewCount: 110,
    avatar: "VS",
    availableToday: true,
  },
  {
    id: "DOC-6",
    name: "Dr. Ananya Roy",
    qualification: "MS (Orthopedics)",
    specialization: "Joint Replacement & Spine Surgeon",
    department: "Orthopedics",
    experience: "11+ Years Exp.",
    consultationFee: "$75.00",
    availability: "Available Today (4 Slots)",
    rating: "4.8",
    reviewCount: 75,
    avatar: "AR",
    availableToday: true,
  },
];

export const MOCK_VISIT_RECORDS: MedicalVisitRecord[] = [
  {
    id: "VIS-2024-001",
    date: "March 12, 2024",
    time: "10:30 AM",
    department: "Cardiology",
    doctor: "Dr. Arjun Mehta",
    specialty: "Senior Cardiologist",
    diagnosis: "Mild Hypertension, R/O Angina",
    notes:
      "Patient reported occasional chest tightness after exertion. BP is elevated (145/92). Advised lifestyle changes and prescribed medication to manage blood pressure. Follow-up in 2 weeks.",
    prescriptions: ["Amlodipine 5mg OD", "Atorvastatin 20mg HS"],
    status: "Completed",
  },
  {
    id: "VIS-2023-089",
    date: "December 04, 2023",
    time: "02:15 PM",
    department: "General Medicine",
    doctor: "Dr. Priya Sharma",
    specialty: "Endocrinologist",
    diagnosis: "Acute Bronchitis & Type 2 Diabetes Review",
    notes:
      "Presenting with productive cough, mild fever, and fatigue for 4 days. Auscultation reveals bilateral rhonchi. Prescribed antibiotics and symptomatic relief.",
    prescriptions: [
      "Amoxicillin 500mg TDS",
      "Paracetamol 500mg SOS",
      "Cough Syrup 10ml BD",
    ],
    status: "Completed",
  },
  {
    id: "VIS-2023-045",
    date: "July 18, 2023",
    time: "11:00 AM",
    department: "Cardiology",
    doctor: "Dr. Arjun Mehta",
    specialty: "Senior Cardiologist",
    diagnosis: "Annual Cardiac Check-up",
    notes:
      "Routine check-up. ECG normal. TMT negative for ischemia. Lipid profile shows borderline high LDL. Advised diet control and regular aerobic exercise.",
    prescriptions: ["Rosuvastatin 10mg OD"],
    status: "Completed",
  },
];

export const MOCK_PRESCRIPTION_RECORDS: PrescriptionRecord[] = [
  {
    id: "RX-8910",
    doctor: "Dr. Arjun Mehta",
    department: "Cardiology",
    issueDate: "2024-03-12",
    status: "Active",
    diagnosis: "Mild Hypertension",
    followUpDate: "2024-04-05",
    medicines: [
      {
        name: "Amlodipine 5mg",
        dosage: "1 Tablet OD (Once Daily)",
        frequency: "Morning after breakfast",
        duration: "30 Days",
        instructions: "Take regularly at 9 AM. Monitor BP weekly.",
      },
      {
        name: "Atorvastatin 20mg",
        dosage: "1 Tablet HS (At Bedtime)",
        frequency: "Night before sleep",
        duration: "30 Days",
        instructions: "Avoid grapefruit juice while taking this medication.",
      },
    ],
  },
  {
    id: "RX-8421",
    doctor: "Dr. Priya Sharma",
    department: "General Medicine",
    issueDate: "2023-12-04",
    status: "Expired",
    diagnosis: "Acute Bronchitis",
    followUpDate: "2023-12-18",
    medicines: [
      {
        name: "Amoxicillin 500mg",
        dosage: "1 Capsule TDS (Three times daily)",
        frequency: "Every 8 hours",
        duration: "7 Days",
        instructions:
          "Complete full 7-day antibiotic course even if symptoms resolve.",
      },
      {
        name: "Paracetamol 500mg",
        dosage: "1 Tablet SOS (As needed)",
        frequency: "Max 3 tablets daily",
        duration: "5 Days",
        instructions: "Take only if fever exceeds 100°F.",
      },
    ],
  },
  {
    id: "RX-7732",
    doctor: "Dr. Arjun Mehta",
    department: "Cardiology",
    issueDate: "2023-07-18",
    status: "Refilled",
    diagnosis: "Hyperlipidemia",
    followUpDate: "2023-10-18",
    medicines: [
      {
        name: "Rosuvastatin 10mg",
        dosage: "1 Tablet OD",
        frequency: "Nightly",
        duration: "90 Days",
        instructions: "Repeat lipid profile test prior to next follow-up.",
      },
    ],
  },
];

export const INITIAL_INVOICES: PatientInvoice[] = [
  {
    id: "INV-2024-001",
    date: "2024-03-12",
    dueDate: "2024-03-26",
    doctor: "Dr. Arjun Mehta",
    department: "Cardiology",
    amount: "$97.60",
    numericAmount: 97.6,
    status: "Paid",
    patientPayable: "$97.60",
    paymentRef: "TXN-98214-88A",
    paymentDate: "2024-03-12 11:30 AM",
    paymentMethod: "Visa Credit Card **** 4242",
    items: [
      {
        description: "Cardiology Specialist OPD Consultation",
        category: "Consultation",
        cost: "$65.00",
      },
      {
        description: "Routine 12-Lead ECG Screening",
        category: "Diagnostics",
        cost: "$25.00",
      },
      {
        description: "Pharmacy Prescription (Amlodipine + Atorvastatin)",
        category: "Pharmacy",
        cost: "$57.60",
      },
    ],
  },
  {
    id: "INV-2024-002",
    date: "2024-03-22",
    dueDate: "2024-04-05",
    doctor: "Dr. Priya Sharma",
    department: "General Medicine",
    amount: "$45.00",
    numericAmount: 45.0,
    status: "Pending",
    patientPayable: "$45.00",
    items: [
      {
        description: "General OPD Consultation",
        category: "Consultation",
        cost: "$45.00",
      },
      {
        description: "Electronic Health Record Processing",
        category: "Administrative",
        cost: "$20.00",
      },
    ],
  },
  {
    id: "INV-2024-003",
    date: "2024-03-28",
    dueDate: "2024-04-11",
    doctor: "Dr. Rajesh Kapoor",
    department: "Neurology",
    amount: "$120.00",
    numericAmount: 120.0,
    status: "Pending",
    patientPayable: "$120.00",
    items: [
      {
        description: "Neurology Comprehensive Evaluation",
        category: "Consultation",
        cost: "$100.00",
      },
      {
        description: "EEG Test Preliminary Screening",
        category: "Diagnostics",
        cost: "$80.00",
      },
    ],
  },
  {
    id: "INV-2023-089",
    date: "2023-12-04",
    dueDate: "2023-12-18",
    doctor: "Dr. Priya Sharma",
    department: "General Medicine",
    amount: "$85.00",
    numericAmount: 85.0,
    status: "Paid",
    patientPayable: "$85.00",
    paymentRef: "TXN-84102-12C",
    paymentDate: "2023-12-04 03:00 PM",
    paymentMethod: "Mastercard Debit **** 1092",
    items: [
      {
        description: "General OPD Consultation & Physical Exam",
        category: "Consultation",
        cost: "$60.00",
      },
      {
        description: "Acute Bronchitis Medication Package",
        category: "Pharmacy",
        cost: "$65.00",
      },
    ],
  },
  {
    id: "INV-2023-045",
    date: "2023-07-18",
    dueDate: "2023-08-01",
    doctor: "Dr. Arjun Mehta",
    department: "Cardiology",
    amount: "$210.00",
    numericAmount: 210.0,
    status: "Paid",
    patientPayable: "$210.00",
    paymentRef: "TXN-71930-99F",
    paymentDate: "2023-07-18 12:15 PM",
    paymentMethod: "Apple Pay / Digital Wallet",
    items: [
      {
        description: "Annual Cardiac Health Checkup Package",
        category: "Checkup",
        cost: "$250.00",
      },
      {
        description: "Treadmill Stress Test (TMT)",
        category: "Diagnostics",
        cost: "$110.00",
      },
    ],
  },
];

export const PAYMENT_HISTORY_RECORDS: PaymentHistoryRecord[] = [
  {
    id: "PAY-2024-001",
    date: "Mar 12, 2024",
    time: "11:30 AM",
    amount: "$97.60",
    method: "Visa Credit Card **** 4242",
    referenceNumber: "TXN-98214-88A",
    invoiceId: "INV-2024-001",
    status: "Completed",
  },
  {
    id: "PAY-2023-089",
    date: "Dec 04, 2023",
    time: "03:00 PM",
    amount: "$85.00",
    method: "Mastercard Debit **** 1092",
    referenceNumber: "TXN-84102-12C",
    invoiceId: "INV-2023-089",
    status: "Completed",
  },
  {
    id: "PAY-2023-045",
    date: "Jul 18, 2023",
    time: "12:15 PM",
    amount: "$210.00",
    method: "Apple Pay / Digital Wallet",
    referenceNumber: "TXN-71930-99F",
    invoiceId: "INV-2023-045",
    status: "Completed",
  },
];
